Hw07 file copying
andreyAKor/otus_hw pull request #7
Opened 2020-05-10 16:14 UTC by andreyAKor

## Домашнее задание №7 «Утилита для копирования файлов»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-05-11 06:40 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/86835/6030/

Здравствуйте!

Давайте сделаем так, чтобы в PR присутствовала только 7 домашка.
Спасибо

2020-05-11 08:33 UTC, andreyAKor commented
Добрый день!
Не заметил как затесался коммит от 6й домашки. Все поправил.

2020-05-14 05:56 UTC, Antonboom approved these changes
Хорошее, лаконичное решение.

Принято
10 / 10

2020-05-14 08:39 UTC, andreyAKor commented
Спасибо!

2020-05-25 04:58 UTC, merged